# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  slack_team_id:    "<%= ENV["SLACK_TEAM_ID"] %>"
  slack_app_id:     "<%= ENV["SLACK_APP_ID"] %>"
  slack_app_secret: "<%= ENV["SLACK_APP_SECRET"] %>"
  slack_bot_name:   "<%= ENV["SLACK_BOT_NAME"] %>"
  slack_bot_token:  "<%= ENV["SLACK_BOT_TOKEN"] %>"
  hipchat_token:    "<%= ENV["HIPCHAT_TOKEN"] %>"
  hipchat_server:   "<%= ENV["HIPCHAT_SERVER"] %>"

development:
  <<: *default
  secret_key_base: 1e552ca669d2a5e2eb614ac6e49b917b6c148b5c88d69bd7430fd9f9ece77379c588e56e8ce347890c72d46970468e6e659f0f6c7abe4872a0b35ce2e0a78d4c

test:
  <<: *default
  secret_key_base: 2ecb098f772e454eb9e3d4b425a0a146008744565fe10fa95a780f9eaa33be96d27bdfbcfc2fefdc7223e46a630c34bac6f6fe87b344a202e468fc7f74f2b135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base:  "<%= ENV["SECRET_KEY_BASE"] %>"
